[package]
edition = "2021"
name = "grid_coloring_problem_solver"
version = "0.1.0"
description = "Grid Coloring Problem solver"
repository = "https://github.com/tobiges/grid_coloring_problem_solver"

[profile.dev]
opt-level = 3

[dependencies]
anyhow = "1.0.52"
varisat = "0.2.2"
